services:

  api:
    build:
      context: .
    environment:
      - ENV=dev
      - DATABASE=projects
      - HOST=mysql
      - PORT=3306
      - USERNAME=adam
      - PASSWORD=123
    ports:
        - "8099:8099"
    networks:
      - fastapi-network
    depends_on:
      - mysql
    profiles:
      - dev

  mysql:
    image: "mysql"
    env_file:
      - ./env_vars
    volumes:
      - mysql_db_storage:/var/lib/mysql:rw
    networks:
      - fastapi-network
    profiles:
      - dev

networks:
  fastapi-network:
    driver: bridge

volumes:
  mysql_db_storage:

